version: "3"
services:

  db:
    #restart: always
    container_name: 'postgres_dev'
    image: postgres
    environment:
        POSTGRES_PASSWORD: password123
    ports:
        - "5432:5432"
    volumes:
        - pgdata:/var/lib/postgresql/data/


  backend:
    #restart: always
    build: ./backend
    container_name: 'backend'
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/web
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: 'frontend'
    command: npm run start
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

volumes:
  pgdata:

