FROM node
MAINTAINER CHENG-HUNG,WANG

# set working directory
RUN mkdir /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
# ENV PATH /usr/src/app/node_modules/.bin:$PATH

#RUN npx create-react-app app
#RUN npm install 
